fix scripts

diff --git a/.local/scripts/fpreviewer b/.local/scripts/fpreviewer
--- a/.local/scripts/fpreviewer
+++ b/.local/scripts/fpreviewer
@@ -5,40 +5,26 @@ die() {
     exit 1
 }
 
-cmdexists() {
-    command -v "$1" >/dev/null 2>&1
-}
-
 mbat() {
     local start="$1"
     local end="$2"
     local ln="$3"
     local file="$4"
 
-    if cmdexists bat; then
-        bat --highlight-line "$ln" \
-            --paging never \
-            --color always \
-            --number \
-            --theme ansi \
-            --line-range "$start":"$end" \
-            "$file"
-    else
-        awk '
-            NR == '$ln' {
-                underbeg = "\033[4m"
-                underend = "\033[0m"
-            }
-            NR >= '$start' {
-                printf("%s%d %s%s\n", underbeg, NR, $0, underend)
-                underbeg = ""
-                underend = ""
-            }
-            NR > '$end' {
-                exit
-            }
-        ' "$file"
-    fi
+    awk '
+        NR == '"$ln"' {
+            underbeg = "\033[4m"
+            underend = "\033[0m"
+        }
+        NR >= '"$start"' {
+            printf("%s%d %s%s\n", underbeg, NR, $0, underend)
+            underbeg = ""
+            underend = ""
+        }
+        NR > '"$end"' {
+            exit
+        }
+    ' "$file"
 }
 
 file=/dev/stdin
@@ -54,7 +40,7 @@ done
 
 [[ -e $file ]] || die "file '$file' does not exist"
 positiveintre='^[0-9]+$'
-[[ $linenr =~ $re ]] || die "invalid line number '$linenr'"
+[[ $linenr =~ $positiveintre ]] || die "invalid line number '$linenr'"
 
 shopt -s checkwinsize; (:)
 center=$((LINES / 2))
