fix install-dotfiles

diff --git a/.local/scripts/install-dotfiles b/.local/scripts/install-dotfiles
--- a/.local/scripts/install-dotfiles
+++ b/.local/scripts/install-dotfiles
@@ -11,12 +11,14 @@ print_help() {
     echo "-c    Specify separate-git-dir. Default is $confDir"
 }
 
+git_bare() {
+    /usr/bin/git --git-dir="$destination/$confDir" --work-tree="$destination" "$@"
+}
 
 clone_dotfiles() {
     # $1 -> path to repo
     # $2 -> directory to copy to
-    # $3 -> conf dir (.myconf)
-    /usr/bin/git clone --separate-git-dir="$2"/"$3" "$1" "$2"
+    /usr/bin/git clone --bare "$1" "$2"
 }
 
 repo="https://github.com/fioriandrea/dotfiles"
@@ -36,7 +38,18 @@ do
 done
 
 tmpdir="$(mktemp -d)"
+if ![ -d "$tmpdir" ]
+then
+    echo "failed to create tmpdir" >&2
+    exit 2
+fi
+
 tmpdir="${tmpdir%/}"
+destination="${destination%/}"
+
 clone_dotfiles "$repo" "$tmpdir" "$confDir"
-rsync -av --progress "$tmpdir"/ "$destination"
+cp -r "$tmpdir"/ "$destination/$confDir"
+git_bare checkout
+git_bare config --local status.showUntrackedFiles no
+
 rm -rf "$tmpdir"
